export default {
  matrix6x6: {
    matMapColors: [
      ['level6', 'level5', 'level4', 'level3', 'level2', 'level1'],
      ['level7', 'level6', 'level5', 'level4', 'level3', 'level2'],
      ['level8', 'level7', 'level6', 'level5', 'level4', 'level3'],
      ['level9', 'level8', 'level7', 'level6', 'level5', 'level4'],
      ['level10', 'level9', 'level8', 'level7', 'level6', 'level5'],
      ['level10', 'level10', 'level9', 'level8', 'level7', 'level6'],
    ],
    flatMapColors: [
      'level6',
      'level5',
      'level4',
      'level3',
      'level2',
      'level1',
      'level7',
      'level6',
      'level5',
      'level4',
      'level3',
      'level2',
      'level8',
      'level7',
      'level6',
      'level5',
      'level4',
      'level3',
      'level9',
      'level8',
      'level7',
      'level6',
      'level5',
      'level4',
      'level10',
      'level9',
      'level8',
      'level7',
      'level6',
      'level5',
      'level10',
      'level10',
      'level9',
      'level8',
      'level7',
      'level6',
    ],
    severityEquivalence: ['L', 'M', 'M', 'MH', 'MH', 'VH'],
    totalBuckets: 12,
  },
};
