export const safeguards = [
  'End of Line Deflagation Arrestor',
  'In-Line Deflagation Arrestor',
  'Detonation Flame Arrestor, where DDT cannot be ruled out (stable)',
  'Detonation Flame Arrestor, where DDT could occur (unstable)',
  'Restriction Orifice',
  'Mechanical Stop to Limit Travel',
  'Overflow Line',
  'Overflow line with Passive Fluid or Rupture Disc',
  'Overflow Line Containing a Fluid with Potential to Freeze or Isolation Valves',
  'Dike, Bund, Berm',
  'Remote Impoindment Basins',
  'Fire Proofing on Vessel/Structure',
  'Basic Process Control Systems (BPCS)',
  'Process Alarm with Operator Response',
  'Safety Instrument System (SIS) Function',
  'Rapture Disc',
  'Pressure-Vacuum Valve',
  'Vacuum Breaker',
  'Check Valve',
];
